# This copies the DigitalOcean registry secret from kube-system to default namespace
# Run: kubectl apply -f k8s/copy-registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lyku
  namespace: default
  annotations:
    digitalocean.com/dosecret-identifier: lyku
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: 'PLACEHOLDER_COPY_FROM_KUBE_SYSTEM'
