apiVersion: v1
kind: ServiceAccount
metadata:
  name: indy-job-deleter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: job-deleter
rules:
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['delete', 'get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: indy-job-deleter
  namespace: default
subjects:
  - kind: ServiceAccount
    name: indy-job-deleter
    namespace: default
roleRef:
  kind: Role
  name: job-deleter
  apiGroup: rbac.authorization.k8s.io
