apiVersion: batch/v1
kind: CronJob
metadata:
  name: indy-reindex-scheduled
  namespace: default
spec:
  schedule: '0 2 * * *' # Run daily at 2 AM
  concurrencyPolicy: Forbid # Don't allow concurrent runs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400 # Clean up after 24 hours
      backoffLimit: 3
      activeDeadlineSeconds: 7200
      template:
        metadata:
          labels:
            app: indy-reindex
            job: elasticsearch-reindex-scheduled
        spec:
          restartPolicy: OnFailure
          containers:
            - name: indy
              image: registry.digitalocean.com/lyku/lyku:indy
              imagePullPolicy: Always
              command: ['bun', './serve.js']
              envFrom:
                - secretRef:
                    name: doppler-token-secret
              env:
                - name: NODE_ENV
                  value: 'production'
                - name: BUN_LOG_LEVEL
                  value: 'debug'
                - name: BUN_FORCE_TTY
                  value: '1'
                - name: FORCE_COLOR
                  value: '1'
                - name: HCAPTCHA_SECRET
                  value: '${HCAPTCHA_SECRET}'
                - name: PG_CONNECTION_STRING
                  value: '${PG_CONNECTION_STRING}'
                - name: CF_API_TOKEN
                  value: '${CF_API_TOKEN}'
                - name: CF_ID
                  value: '${CF_ID}'
                - name: CH_ENDPOINT
                  value: '${CH_ENDPOINT}'
                - name: CH_USERNAME
                  value: '${CH_USERNAME}'
                - name: CH_PASSWORD
                  value: '${CH_PASSWORD}'
                - name: ELASTIC_API_ENDPOINT
                  value: '${ELASTIC_API_ENDPOINT}'
                - name: ELASTIC_API_KEY
                  value: '${ELASTIC_API_KEY}'
                - name: MUX_TOKEN_ID
                  value: '${MUX_TOKEN_ID}'
                - name: MUX_TOKEN_SECRET
                  value: '${MUX_TOKEN_SECRET}'
                - name: PUBLIC_CF_HASH
                  value: '${PUBLIC_CF_HASH}'
                - name: WEBUI_DOMAIN
                  value: '${WEBUI_DOMAIN}'
                - name: SERVICE_DOMAIN
                  value: '${SERVICE_DOMAIN}'
                - name: NODE_TLS_REJECT_UNAUTHORIZED
                  value: '0'
                - name: REDIS_INTERNAL_CONNECTION_STRING
                  value: '${REDIS_INTERNAL_CONNECTION_STRING}'
                - name: ORIGIN_CERTIFICATE
                  value: |
                    ${ORIGIN_CERTIFICATE}
                - name: PRIVATE_KEY
                  value: |
                    ${PRIVATE_KEY}
                # For scheduled runs, reindex last 7 days by default
                - name: START_DATE
                  value: "$(date -d '7 days ago' +%Y-%m-%d)"
                - name: END_DATE
                  value: '$(date +%Y-%m-%d)'
              resources:
                requests:
                  memory: '2Gi'
                  cpu: '500m'
                limits:
                  memory: '4Gi'
                  cpu: '2000m'
          imagePullSecrets:
            - name: lyku
