apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./micro.yaml

patches:
  - target:
      kind: Deployment
      name: ${SERVICE_NAME}
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: lyku/lyku:${SERVICE_NAME}
