apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
  namespace: lyku
  labels:
    app: ${DEPLOYMENT_NAME}
    app.kubernetes.io/component: lyku-route # Added for ServiceMonitor
    app.kubernetes.io/name: lyku
    app.kubernetes.io/instance: ${SERVICE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT_NAME}
        app.kubernetes.io/component: lyku-route # Added for ServiceMonitor
        app.kubernetes.io/name: lyku
        app.kubernetes.io/instance: ${SERVICE_NAME}
      annotations:
        prometheus.io/scrape: 'true' # Enable Prometheus scraping
        prometheus.io/port: '3000' # Port for metrics
        prometheus.io/path: '/metrics' # Metrics endpoint path
    spec:
      imagePullSecrets:
        - name: lyku
      containers:
        - name: ${DEPLOYMENT_NAME}
          image: ${IMAGE}
          imagePullPolicy: Always
          command: ['bun']
          args:
            - './serve.js'
          envFrom:
            - secretRef:
                name: doppler-token-secret
          env:
            - name: NODE_ENV
              value: 'production'
            - name: BUN_LOG_LEVEL
              value: 'debug'
            - name: BUN_FORCE_TTY
              value: '1'
            - name: FORCE_COLOR
              value: '1'
            - name: HCAPTCHA_SECRET
              value: '${HCAPTCHA_SECRET}'
            - name: PG_CONNECTION_STRING
              value: '${PG_CONNECTION_STRING}'
            - name: CF_API_TOKEN
              value: '${CF_API_TOKEN}'
            - name: CF_ID
              value: '${CF_ID}'
            - name: CH_ENDPOINT
              value: '${CH_ENDPOINT}'
            - name: CH_USERNAME
              value: '${CH_USERNAME}'
            - name: CH_PASSWORD
              value: '${CH_PASSWORD}'
            - name: ELASTIC_CONNECTION_STRING
              value: '${ELASTIC_CONNECTION_STRING}'
            - name: MUX_TOKEN_ID
              value: '${MUX_TOKEN_ID}'
            - name: MUX_TOKEN_SECRET
              value: '${MUX_TOKEN_SECRET}'
            - name: NATS_CONNECTION_STRING
              value: '${NATS_CONNECTION_STRING}'
            - name: PUBLIC_CF_HASH
              value: '${PUBLIC_CF_HASH}'
            - name: WEBUI_DOMAIN
              value: '${WEBUI_DOMAIN}'
            - name: SERVICE_DOMAIN
              value: '${SERVICE_DOMAIN}'
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: REDIS_INTERNAL_CONNECTION_STRING
              value: '${REDIS_INTERNAL_CONNECTION_STRING}'
            - name: ORIGIN_CERTIFICATE
              value: |
                ${ORIGIN_CERTIFICATE}
            - name: PRIVATE_KEY
              value: |
                ${PRIVATE_KEY}
          ports:
            - name: http # Named port for ServiceMonitor
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: '${MEMORY_REQUEST}'
              cpu: '${CPU_REQUEST}'
            limits:
              memory: '${MEMORY_LIMIT}'
              cpu: '${CPU_LIMIT}'
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 300
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT_NAME}-service
  namespace: lyku
  labels:
    app: ${DEPLOYMENT_NAME}
    app.kubernetes.io/component: lyku-route # Added for ServiceMonitor
    app.kubernetes.io/name: lyku
    app.kubernetes.io/instance: ${SERVICE_NAME}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: ${DEPLOYMENT_NAME}
  ports:
    - name: http # Named port required by ServiceMonitor
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: lyku
  namespace: kube-system
  annotations:
    digitalocean.com/dosecret-identifier: lyku
type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: ${DOCKER_CREDENTIALS}
