apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
  labels:
    app: ${DEPLOYMENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT_NAME}
    spec:
      imagePullSecrets:
        - name: lyku
      containers:
        - name: ${DEPLOYMENT_NAME}
          image: registry.digitalocean.com/lyku/lyku:${SERVICE_NAME}
          imagePullPolicy: Always
          command: ['bun']
          args:
            - './serve.js'
          envFrom:
            - secretRef:
                name: doppler-token-secret
          env:
            - name: NODE_ENV
              value: 'production'
            - name: BUN_LOG_LEVEL
              value: 'debug'
            - name: BUN_FORCE_TTY
              value: '1'
            - name: FORCE_COLOR
              value: '1'
            - name: DATABASE_URL
              value: '${DATABASE_URL}'
            - name: CF_API_TOKEN
              value: '${CF_API_TOKEN}'
            - name: CF_ID
              value: '${CF_ID}'
            - name: ELASTIC_API_ENDPOINT
              value: '${ELASTIC_API_ENDPOINT}'
            - name: ELASTIC_API_KEY
              value: '${ELASTIC_API_KEY}'
            - name: PUBLIC_CF_HASH
              value: '${PUBLIC_CF_HASH}'
            - name: WEBUI_DOMAIN
              value: '${WEBUI_DOMAIN}'
            - name: SERVICE_DOMAIN
              value: '${SERVICE_DOMAIN}'
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '160Mi'
              cpu: '5m'
            limits:
              memory: '200Mi'
              cpu: '200m'
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT_NAME}-service
spec:
  selector:
    app: ${DEPLOYMENT_NAME}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: lyku
  namespace: kube-system
  annotations:
    digitalocean.com/dosecret-identifier: lyku
type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: ${DOCKER_CREDENTIALS}
