compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
services = [
  { binding = "ES_PROXY", service = "elasticsearch-proxy" }
]
[env.production]
name = "lyku-webui"

[site]
bucket = "./dist/apps/webui/"

[build]
command = "bun run build"

[build.upload]
format = "modules"
dir = "./dist/apps/webui/"

# Optional: Configure environment variables
# [vars]
# MY_VARIABLE = "production_value"

# Optional: Configure KV Namespaces
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxx"

# Optional: Configure Durable Objects
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"
