#! /bin/bash
projectName=$1
if [ -z "$projectName" ]; then
  echo "Error: projectName is missing"
  exit 1
fi
kubectl delete deployment lyku-${projectName} --ignore-not-found
node ibuild.ts apps/routes/${projectName}/serve.ts dist/apps/routes/${projectName}
