#!/bin/bash
# deploy-route.sh

# Set KUBECONFIG to the specified file
export KUBECONFIG=C:\Users\nickm\lyk8s-kubeconfig.yaml

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <service-name>"
    exit 1
fi

export SERVICE_NAME=$1
export IMAGE=registry.digitalocean.com/lyku/lyku:${SERVICE_NAME}

echo "SERVICE_NAME: ${SERVICE_NAME}"

configLocation=~/lyk8s-kubeconfig.yaml
export config=--kubeconfig=${configLocation}
export DEPLOYMENT_NAME=lyku-${SERVICE_NAME}

echo "Deleting deployment ${DEPLOYMENT_NAME}"
kubectl delete deployment ${DEPLOYMENT_NAME} --ignore-not-found ${config}

echo "Deploying ${SERVICE_NAME} with image ${IMAGE}"

# Check if the deployment exists
if envsubst < k8s/micro.yaml | kubectl get deployment ${DEPLOYMENT_NAME} ${config} >/dev/null 2>&1; then
    # Update the deployment with the new image
    envsubst < k8s/micro.yaml | kubectl set image deployment/${DEPLOYMENT_NAME} ${DEPLOYMENT_NAME}=${IMAGE} ${config}
    echo "Deployment ${DEPLOYMENT_NAME} updated to image ${IMAGE}"
    # Force redeployment by triggering a rollout restart
    # kubectl rollout restart deployment/${SERVICE_NAME} ${config}
else
    # Apply the micro.yaml to create the deployment if it does not exist
    envsubst < k8s/micro.yaml | kubectl apply -f - ${config}
    echo "Deployment ${DEPLOYMENT_NAME} created with image ${IMAGE}"
fi

echo ""
echo "✅ Deployment complete!"
echo "📊 To create a monitoring dashboard, run: ./scripts/graph-route $SERVICE_NAME"
