apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ${SERVICE_NAME}
          image: nicolemuzzin/lyku:${SERVICE_NAME}
          imagePullPolicy: Always
          command: ['bun']
          args:
            - '--eval'
            - "process.stdout.isTTY = true; console.log('Container starting...'); require('./index.js')"
          env:
            - name: NODE_ENV
              value: 'production'
            - name: BUN_LOG_LEVEL
              value: 'debug'
            - name: BUN_FORCE_TTY
              value: '1'
            - name: FORCE_COLOR
              value: '1'
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}-service
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
